import {
  AddRegular,
  AlertOnRegular,
  AlertUrgentRegular,
  ArrowDownloadRegular,
  ArrowLeftRegular,
  ArrowMaximizeRegular,
  ArrowMinimizeRegular,
  ArrowRepeat1Regular,
  ArrowRepeatAllRegular,
  ArrowRightRegular,
  ArrowShuffleRegular,
  ArrowSyncRegular,
  ArrowUploadRegular,
  CalculatorRegular,
  CalendarRegular,
  CameraRegular,
  CheckmarkRegular,
  ChevronDownRegular,
  ChevronLeftRegular,
  ChevronRightRegular,
  ChevronUpRegular,
  ClipboardRegular,
  ClockRegular,
  ColorRegular,
  DeleteRegular,
  DesktopRegular,
  DismissRegular,
  DocumentTextRegular,
  EditRegular,
  ErrorCircleRegular,
  EyeOffRegular,
  EyeRegular,
  FlashRegular,
  FolderRegular,
  GiftRegular,
  HomeRegular,
  InfoRegular,
  KeyboardRegular,
  MusicNote1Regular,
  NavigationRegular,
  OpenRegular,
  PauseRegular,
  PersonRegular,
  PlayRegular,
  SearchRegular,
  SettingsRegular,
  ShareRegular,
  Speaker0Regular,
  Speaker1Regular,
  StarFilled,
  StarRegular,
  TagRegular,
  TaskListLtrRegular,
  VideoRegular,
  WindowRegular,
} from "@fluentui/react-icons";

/**
 * Iconos de la aplicación.
 *
 * Antes eran letras de `Segoe Fluent Icons`: un número del área de uso privado de la fuente (0xE72B, 0xE8A5…) que se
 * pintaba en un `<span>`. En Windows salía bien; en cualquier otro sistema la fuente no está, el navegador no
 * encuentra el carácter y pinta un cuadrado vacío. Como Linux también usa Nexo, ahora son los iconos SVG de
 * `@fluentui/react-icons` (los mismos del lenguaje de diseño Fluent, con licencia MIT), que no dependen de ninguna
 * fuente instalada.
 *
 * Cada nombre sigue siendo el mismo y `<Glifo>` se sigue usando igual, así que ningún otro archivo cambia.
 */

export const GLIFOS = {
  atras: ArrowLeftRegular,
  adelante: ArrowRightRegular,
  menu: NavigationRegular,
  inicio: HomeRegular,
  video: VideoRegular,
  musica: MusicNote1Regular,
  documentos: DocumentTextRegular,
  configuracion: SettingsRegular,
  atajos: KeyboardRegular,
  buscar: SearchRegular,
  minimizar: ArrowMinimizeRegular,
  maximizar: ArrowMaximizeRegular,
  restaurar: WindowRegular,
  cerrar: DismissRegular,
  anterior: ArrowLeftRegular,
  reproducir: PlayRegular,
  pausar: PauseRegular,
  siguiente: ArrowRightRegular,
  aleatorio: ArrowShuffleRegular,
  repetir: ArrowRepeatAllRegular,
  repetirUna: ArrowRepeat1Regular,
  volumen: Speaker1Regular,
  silencio: Speaker0Regular,
  expandir: ArrowMaximizeRegular,
  contraer: ChevronLeftRegular,
  arriba: ChevronUpRegular,
  abajo: ChevronDownRegular,
  mas: AddRegular,
  agregar: AddRegular,
  actualizar: ArrowSyncRegular,
  descargar: ArrowDownloadRegular,
  cargar: ArrowUploadRegular,
  eliminar: DeleteRegular,
  externo: OpenRegular,
  aviso: AlertUrgentRegular,
  error: ErrorCircleRegular,
  info: InfoRegular,
  exito: CheckmarkRegular,
  paleta: ColorRegular,
  pantalla: DesktopRegular,
  carpeta: FolderRegular,
  editar: EditRegular,
  informacion: InfoRegular,
  chevronDerecha: ChevronRightRegular,
  chevronIzquierda: ChevronLeftRegular,
  calendario: CalendarRegular,
  persona: PersonRegular,
  campana: AlertOnRegular,
  regalo: GiftRegular,
  reloj: ClockRegular,
  compartir: ShareRegular,
  calculadora: CalculatorRegular,
  tarea: TaskListLtrRegular,
  examen: ClipboardRegular,
  etiqueta: TagRegular,
  camara: CameraRegular,
  energia: FlashRegular,
  favorito: StarRegular,
  favoritoLleno: StarFilled,
  ojo: EyeRegular,
  ojoTachado: EyeOffRegular,
  chevronAbajo: ChevronDownRegular,
  chevronArriba: ChevronUpRegular,
} as const;

export type NombreGlifo = keyof typeof GLIFOS;

/** Un icono concreto de Fluent. */
export type ComponenteGlifo = (typeof GLIFOS)[NombreGlifo];

/** El icono pedido, como componente. */
export const glifo = (nombre: NombreGlifo): ComponenteGlifo => GLIFOS[nombre];
