import type { ToolDefinition, ToolId } from "@/types/documents";
import { T } from "@/lib/i18n";
import { MAX_FILES_PER_BATCH } from "./limits";

/** Catálogo de herramientas de Documentos. Todas funcionan dentro de la aplicación. */
export const TOOLS: readonly ToolDefinition[] = [
  {
    id: "word-to-pdf",
    action: T("Convertir a PDF"),
    name: T("Word a PDF"),
    description: T("Convierte documentos de Word (.docx) en PDF."),
    accepts: ["word"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "pdf-to-word",
    action: T("Convertir a Word"),
    name: T("PDF a Word"),
    description: T("Convierte un PDF en un documento .docx editable."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "DOCX",
  },
  {
    id: "excel-to-pdf",
    action: T("Convertir a PDF"),
    name: T("Excel a PDF"),
    description: T("Convierte hojas de cálculo .xlsx en PDF."),
    accepts: ["excel"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "powerpoint-to-pdf",
    action: T("Convertir a PDF"),
    name: T("PowerPoint a PDF"),
    description: T("Convierte presentaciones .pptx en PDF."),
    accepts: ["powerpoint"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "merge",
    action: T("Unir PDF"),
    name: T("Unir PDF"),
    description: T("Combina varios PDF en uno solo. Ordénalos arrastrando."),
    accepts: ["pdf"],
    minFiles: 2,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "split",
    action: T("Dividir PDF"),
    name: T("Dividir PDF"),
    description: T("Extrae páginas o rangos eligiéndolos en las miniaturas."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: 1,
    output: "PDF",
  },
  {
    id: "compress",
    action: T("Comprimir PDF"),
    name: T("Comprimir PDF"),
    description: T("Reduce el peso con tres niveles de compresión."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "images-to-pdf",
    action: T("Crear PDF"),
    name: T("Imágenes a PDF"),
    description: T("Junta imágenes JPG y PNG en un PDF con orientación y margen."),
    accepts: ["image"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "pdf-to-images",
    action: T("Convertir a imágenes"),
    name: T("PDF a imágenes"),
    description: T("Convierte cada página en PNG y descárgalas en un ZIP."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "ZIP",
  },
  {
    id: "rotate",
    action: T("Aplicar giro"),
    name: T("Rotar páginas"),
    description: T("Gira páginas sueltas o todo el documento."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: 1,
    output: "PDF",
  },
  {
    id: "protect-pdf",
    action: T("Proteger PDF"),
    name: T("Proteger con contraseña"),
    description: T("Pide una contraseña para poder abrir el PDF, con cualquier lector."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "unlock-pdf",
    action: T("Quitar contraseña"),
    name: T("Quitar contraseña"),
    description: T("Abre un PDF protegido y guarda una copia sin contraseña."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "compare-pdf",
    action: T("Comparar"),
    name: T("Comparar dos PDF"),
    description: T("Resalta el texto que cambió entre dos versiones de un documento."),
    accepts: ["pdf"],
    minFiles: 2,
    maxFiles: 2,
    output: "HTML",
  },
  {
    id: "organize",
    action: T("Guardar PDF"),
    name: T("Organizar páginas"),
    description: T("Cambia el orden de las páginas de un PDF o elimina las que no quieres."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: 1,
    output: "PDF",
  },
  {
    id: "watermark",
    action: T("Poner marca de agua"),
    name: T("Marca de agua"),
    description: T("Escribe un texto (Confidencial, Borrador, tu nombre…) sobre todas las páginas."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "page-numbers",
    action: T("Numerar páginas"),
    name: T("Numerar páginas"),
    description: T("Añade el número de página en el lugar y con el formato que elijas."),
    accepts: ["pdf"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: "PDF",
  },
  {
    id: "ocr",
    action: T("Reconocer texto"),
    name: T("OCR: reconocer texto"),
    description: T("Saca el texto de un PDF escaneado o de una foto, o crea un PDF con texto que se puede buscar y copiar."),
    accepts: ["pdf", "image"],
    minFiles: 1,
    maxFiles: MAX_FILES_PER_BATCH,
    output: T("PDF o texto"),
  },
];

export function getTool(id: ToolId): ToolDefinition {
  const tool = TOOLS.find((t) => t.id === id);
  if (!tool) throw new Error(`Herramienta desconocida: ${id}`);
  return tool;
}

export function isToolId(value: unknown): value is ToolId {
  return typeof value === "string" && TOOLS.some((t) => t.id === value);
}
